trigger:
- main

stages:
- stage: Build
  displayName: Build Stage
  
  jobs:
  - job: Build
    displayName: Build Job
  
    pool:
      vmImage: ubuntu-latest
  
    steps:
      - script: dotnet build

- stage: Publish
  displayName: Publish Stage
  
  jobs:
  - job: Publish
    displayName: Publish Job
  
    pool:
      vmImage: ubuntu-latest
  
    steps:
      - script: dotnet publish --no-build -o ./package

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: './package'
          ArtifactName: 'drop'
          publishLocation: 'Container'