trigger:
- main

stages:
- stage: Build
  displayName: Build Stage
  pool:
      vmImage: ubuntu-latest
  jobs:
  - job: Build
    displayName: Build Job

    steps:
      - script: dotnet build
    
  - job: Publish
    displayName: Publish Job

    steps:
      - script: dotnet publish -o ./package

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: './package'
          ArtifactName: 'drop'
          publishLocation: 'Container'