trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build Stage

  jobs:
  - job: Build
    displayName: Build Job

    steps:
      - script: dotnet build


- stage: Publish
  displayName: Publish Stage
  jobs:
  - job: Publish
    displayName: Publish Job

    steps:
      - script: dotnet publish -o ./package

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: './package'
          ArtifactName: 'drop'
          publishLocation: 'Container'